I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script call
    call ch1
  File "game/ch1.rpy", line 14, in script
    pov "So.  The city.  Sure, it has its problems.  Lots of them.  But one of the benefits is that there's stuff to do even late at night."
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'cityambience.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script call
    call ch1
  File "game/ch1.rpy", line 14, in script
    pov "So.  The city.  Sure, it has its problems.  Lots of them.  But one of the benefits is that there's stuff to do even late at night."
  File "renpy/ast.py", line 684, in execute
    statement_name(getattr(who, "statement_name", "say"))
  File "renpy/ast.py", line 46, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2718, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3276, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3979, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1138, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1116, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1058, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 512, in periodic
    topf = load(filename)
  File "renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'cityambience.wav'.

Windows-7-6.1.7601-SP1
Ren'Py 7.4.8.1895
Tri City Monsters 1.0
Wed Sep 22 14:36:19 2021
